version: "3.8"

services:
  auth-service-db:
    container_name: auth-service-db
    build: 
      context: .
      dockerfile: ./dockerfiles/mssql/Dockerfile
    volumes:
      - ./mssql/data:/var/opt/mssql
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=${AUTH_SERVICE_DB_PASSWORD}
        - AUTH_SERVICE_DB_PASSWORD=${AUTH_SERVICE_DB_PASSWORD}
    ports:
      - ${AUTH_SERVICE_DB_PORT}:1433
    networks:
      - auth-microservice-network
    command: bash -c "./entrypoint.sh"
  auth-service-api:
    container_name: auth-service-api
    build:
      context: .
      dockerfile: ./dockerfiles/node-app/Dockerfile
    depends_on:
      - auth-service-db
    restart: on-failure
    ports:
      - ${AUTH_SERVICE_API_PORT}:${AUTH_SERVICE_API_PORT}
    networks:
      - auth-microservice-network
    command: bash -c "ts-node src/app.ts"

networks:
  auth-microservice-network:
