apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-api-deployment
  labels:
    app: auth-service-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service-api
  template:
    metadata:
      labels:
        app: auth-service-api
    spec:
      containers:
      - name: auth-service-api
        image: cesieatsimages.azurecr.io/auth-service-api-image
        ports:
        - containerPort: 3000
        command: ["bash", "-c", "ts-node src/app.ts"]
        env:
        - name: AUTH_SERVICE_API_PORT
          value: "3000"
        - name: AUTH_SERVICE_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: auth-service-db-config
              key: auth-service-db-host
        - name: AUTH_SERVICE_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: auth-service-db-secret
              key: mssql-sa-password
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-config
              key: rabbitmq-host
      imagePullSecrets:
      - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service-api-service
spec:
  type: NodePort
  selector:
    app: auth-service-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30100


