apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: cesieatsimages.azurecr.io/api-gateway
        ports:
        - containerPort: 80
        command: ["bash", "-c", "ts-node src/app.ts"]
        env:
        - name: API_GATEWAY_PORT
          value: "80"
        - name: USE_HOST_AS_FULL_URL
          value: "true"
        - name: USER_SERVICE_API_HOST
          valueFrom:
            configMapKeyRef:
              name: config-map
              key: user-service-api-host
        - name: AUTH_SERVICE_API_HOST
          valueFrom:
            configMapKeyRef:
              name: config-map
              key: auth-service-api-host
        - name: ORDER_SERVICE_API_HOST
          valueFrom:
            configMapKeyRef:
              name: config-map
              key: order-service-api-host
        - name: CATALOG_SERVICE_API_HOST
          valueFrom:
            configMapKeyRef:
              name: config-map
              key: catalog-service-api-host
        - name: DELIVERY_SERVICE_API_HOST
          valueFrom:
            configMapKeyRef:
              name: config-map
              key: delivery-service-api-host
        - name: NOTIFICATION_SERVICE_API_HOST
          valueFrom:
            configMapKeyRef:
              name: config-map
              key: notification-service-api-host
      imagePullSecrets:
      - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  type: ClusterIP
  selector:
    app: api-gateway
  ports:
    - port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: api-gateway.e073562a5ba0470182a1.northeurope.aksapp.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: api-gateway-service
            port: 
              number: 80
