apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service-db-deployment
  labels:
    app: notification-service-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service-db
  template:
    metadata:
      labels:
        app: notification-service-db
    spec:
      containers:
      - name: notification-service-db
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "admin"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "admin"
        - name: MONGO_INITDB_DATABASE
          value: "admindb"
---
apiVersion: v1
kind: Service
metadata:
  name: notification-db-service
spec:
  selector:
    app: notification-service-db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
