enum QueueName {
    CREATE_ORDER_NOTIFICATION= "CREATE_ORDER_NOTIFICATION",
    MODIFY_ORDER_NOTIFICATION = "MODIFY_ORDER_NOTIFICATION",
    NEW_NOTIFICATION = "NEW_NOTIFICATION",
    NEW_DELIVERY = "NEW_DELIVERY",
    DELIVERY_CARRIED_OUT = "DELIVERY_CARRIED_OUT"
}

export default QueueName;
