enum QueueName {
    CREATE_ORDER_NOTIFICATION= "CREATE_ORDER_NOTIFICATION",
    MODIFY_ORDER_NOTIFICATION = "MODIFY_ORDER_NOTIFICATION",
    NEW_NOTIFICATION = "NEW_NOTIFICATION",
}

export default QueueName;
